### ISSUE TITLE
it not works!!

### ISSUE THREAD

**Issue by masoudabdan** [RobertBoes/inertia-breadcrumbs#2]
when i've check the page props in vue, there isn't breadcrumbs !!!

**Comment by RobertBoes** [comment]
Hi @masoudabdan,

I can't help you with "it not works". This package requires you to use one of the 3 supported breadcrumbs packages, configure them as they describe in their docs and then it'll share the breadcrumbs for the route automatically. It'll only share the breadcrumbs for the current route that have breadcrumbs configured.

If you have any more details or feel like this is an issue, feel free to reopen this issue with a detailed description so I can assist you.
