### ISSUE TITLE
Doesn't work as expected.

### ISSUE THREAD

**Issue by mariusberget92** [RobertBoes/inertia-breadcrumbs#3]
Hi. Followed every step but I can't figure out why it won't share the breadcrumbs to inertia/vue. Breadcrumbs file works if I do this on a non-inertia project, and I have used the package for breadcrumbs before, but not this one which shares the props to inertia/vue. I don't get any errors, so I believe everything is okay syntax wise. The only props I can see being shared is the ones I already shared in the `HandleInertiaRequests` middleware. Is there anyway to add the breadcrumbs directly to the middleware itself, since I can't seem to get it working out of the box? Also, here are some example breadcrumbs I have in my breadcrumbs file if that helps. And below that is the props from VueDevTools.

```
// Dashboard
Breadcrumbs::for('dashboard.index', function (BreadcrumbTrail $trail) {
    $trail->push('Dashboard', route('dashboard.index'));
});

// Dashboard > Users
Breadcrumbs::for('dashboard.users.index', function (BreadcrumbTrail $trail) {
    $trail->parent('dashboard');
    $trail->push('Users', route('dashboard.users.index'));
});

// Dashboard > Users > Create
Breadcrumbs::for('dashboard.users.create', function (BreadcrumbTrail $trail) {
    $trail->parent('dashboard.users.index');
    $trail->push('Create', route('dashboard.users.create'));
});

// Dashboard > Users > Edit
Breadcrumbs::for('dashboard.users.edit', function (BreadcrumbTrail $trail, $user) {
    $trail->parent('dashboard.users.index');
    $trail->push('Edit: '. $user->username, route('dashboard.users.edit', $user));
});
```

```
initialComponent:CreatePage
initialPage:Object
component:"User/CreatePage"
props:Object
  appName:"***"
  auth:Object
  errors:Object (empty)
  flash:Object
  permissions:Array[18]
```

**Comment by mariusberget92** [comment]
Nevermind. Sorry for the inconvenience. I had some typos. Working like a charm. :)

**Comment by baoanhng** [comment]
Okay I got same problem and this reminds me.
