### ISSUE TITLE
Blocking Laravel 10 upgrade

### ISSUE THREAD

**Issue by musiwei** [RobertBoes/inertia-breadcrumbs#4]
Hey Robert, this repo is now blocking us from upgrading to Laravel 10. Could you please have a look when you are available? 

**This is due to Laravel having replaced illuminate/contracts.** 

### See below composer error: 
- Only one of these can be installed: illuminate/contracts[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0, v10.0.0, v10.0.1, v10.0.2, v10.0.3], laravel/framework[v10.0.0, v10.0.1, v10.0.2, v10.0.3].` laravel/framework replaces illuminate/contracts and thus cannot coexist with it.`
- robertboes/inertia-breadcrumbs 0.2.1 requires illuminate/contracts ^9.0 -> satisfiable by illuminate/contracts[v9.0.0, ..., v9.52.0].

**Comment by RobertBoes** [comment]
The hold up was mostly compatibility with third party packages, they've recently added Laravel 10 support, I'll try and publish a new version this weekend. I did publish a pre-release version; https://github.com/RobertBoes/inertia-breadcrumbs/releases/tag/0.3.0-alpha
