### ISSUE TITLE
Named parameter $name overwrites previous argument

### ISSUE THREAD

**Issue by MLDMoritz** [RobertBoes/inertia-breadcrumbs#6]
Fresh Install of Laravel Nova:

PHP 8.2.8
Laravel 9.52.10

![image](https://github.com/RobertBoes/inertia-breadcrumbs/assets/46711821/005996ce-ba86-49f6-bac0-3bbf052822e6)

Disabling the middleware get's rid of the error.

**Comment by RobertBoes** [comment]
Hmm, I don't have a license for Nova, so I can't really test this. But it does I can replicate the issue, I'm going to work on a fix 👍

**Comment by RobertBoes** [comment]
@MLDMoritz should be fixed in [v0.3.2](https://github.com/RobertBoes/inertia-breadcrumbs/releases/tag/0.3.2), let me know if you're still seeing the error
